server:
  port: 8088

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate:
    # 自动更新
    ddl-auto: update
    # 日志中显示sql语句
    show-sql: true
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    timeout: 1000
    pool:
      max-idle: 200
      max-wait: 500
      max-total: 200
      block-when-exhausted: false


# 监控关闭
management:
  security:
    enabled: false